### ISSUE TITLE
strict requirements?

### ISSUE THREAD

**Issue by kibaekkim** [StructJuMP/StructJuMP.jl#25]
`StructJuMP` requires to install both `PIPS-NLP` and `Ipopt`. To me this is quite strict, because `StructJuMP` potentially could support _any solver_. The solvers are used in StructJuMPSolverInterface, even where they seem not necessary. Moreover, `MPI.jl` could also be optional in `StructJuMP`.

Can we relax these requirements (PIPS-NLP, Ipopt, and MPI.jl)?

**Comment by blegat** [comment]
I agree with @kibaekkim 
IMHO `StructJuMP` would benefit from staying more at the modelling level. In the REQUIRE, it is said to need MPI and in the README, it is said to need PIPS and Ipopt while in [StochasticDualDynamicProgramming](https://github.com/blegat/StochasticDualDynamicProgramming.jl), I use StructJuMP without needing any of MPI, PIPS or Ipopt.
I do not think that it is a big issue to require MPI (I may require it in `https://github.com/blegat/StochasticDualDynamicProgramming` in the future anyway) but it may be clearer to move a part of the README to `StructJuMPSolverInterface` if it is specific to that project and just mention in the README that StructJuMP is a modeling interface that is used by several project such as `StructJuMPSolverInterface` and `StochasticDualDynamicProgramming` and could also be used for many other different purposes (any modeling that need parent-children structure).
Of course, I might be misinterpreting the whole project so correct me if I am wrong.

**Comment by joehuchette** [comment]
I agree that the requirements are overly strict. I will try to take a stab this weekend at cleaning this up (along with some of the other open issues).

**Comment by kibaekkim** [comment]
@joehuchette I have already removed a quite on my local. I can create a new branch and put my code there, if you give me an access to create a branch.

**Comment by mlubin** [comment]
@kibaekkim, you don't need write permission for this repo, you can just make a fork

**Comment by kibaekkim** [comment]
@mlubin I already have a folk that keeps a old version of StochJuMP that can still run without PIPS. And Github does not allow me to have two folks for the same project.

**Comment by mlubin** [comment]
@kibaekkim, you should be able to push a new branch to your fork without disrupting what you already have there

**Comment by joehuchette** [comment]
@kibaekkim I believe you already have write access, can you test this out?

**Comment by kibaekkim** [comment]
@mlubin Ah! that should work. @joehuchette Yes, now I can create a branch. Thanks!

**Comment by blegat** [comment]
I see you have create the [remove-pips](https://github.com/StructJuMP/StructJuMP.jl/tree/remove-pips) branch. Can it be merged ? I like the fact that MPI is removed from the REQUIRE file :)

**Comment by blegat** [comment]
@kibaekkim This can be closed now :)

**Comment by kibaekkim** [comment]
@blegat Thanks!
