### ISSUE TITLE
comm as an argument

### ISSUE THREAD

**Issue by kibaekkim** [StructJuMP/StructJuMP.jl#27]
I see the `StructuredModel` function can take `comm` as an argument, in which case it is stored in `StructureData`. But, I also see the other functions just using `COMM_WORLD` for their communicator.  This can certainly go wrong if we have `n` processors in `COMM_WORLD`, create a sub-communicator with `n-1` processors, and pass the sub-communicator to the `StructuredModel` function.

**Comment by fqiang** [comment]
@kibaekkim That's right.  To my understanding the functions (```getMyRank``` and ```getProcIdSet```) should take a ```comm```  as an argument.  Otherwise, it could be a problem when user providing a sub-communicator to build the ```StructuredModel```.
