### ISSUE TITLE
regarding known limitation

### ISSUE THREAD

**Issue by kibaekkim** [StructJuMP/StructJuMP.jl#28]
```
If a constraint declared at the sub-problem uses variable from the parent level, it has to be add using @NLconstraint (instead of @constraint).
```

Is this the limitation of PIPS interface? For linear constraints, @constraint seems working well.

**Comment by fqiang** [comment]
It is not only for PIPS interface. Using @NLconstraint will trigger the passing function at runtime (see [nlp.jl](https://github.com/StructJuMP/StructJuMP.jl/blob/master/src/nlp.jl)) to build the variable map between sub-model and its counter-part from parent model. Later on, this map will be used for recovering the column of the matrix blocks computed by JuMP.

**Comment by joehuchette** [comment]
If I'm understanding @kibaekkim correctly, this works fine:
```jl
parent = StructuredModel(num_scenarios =1)
@variable(parent, x)
child = StructuredModel(parent=m)
@variable(child, y)
@constraint(child, x + y == 1)
```
and so the wording is confusing/incorrect.

**Comment by kibaekkim** [comment]
@joehuchette Right. This seems to be limitation only for nonlinear programs. Is that right, @fqiang ?

**Comment by fqiang** [comment]
Using Joey's example
```julia
getStructure(child).othermap
Dict{JuMP.Variable,JuMP.Variable} with 0 entries
```
If you do ```@NLconstraint(child,x+y==1)```, then
```julia
 getStructure(child).othermap
Dict{JuMP.Variable,JuMP.Variable} with 1 entry:
  x => x
```
You will have this mapping information recorded and use for matrix recovering later.
