### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by blegat** [StructJuMP/StructJuMP.jl#44]
It would be nice to have some documentation for how to model a problem with StructJuMP.
Would you think that the full documentation would fit in the README or that we need to have a separate page with e.g. [JuliaDocs](http://github.com/JuliaDocs) ?

**Comment by joehuchette** [comment]
There's already a toy example in the README, so I think it's reasonable to expand on it at this point. We can move to a separate page if the README gets unwieldy and long.
