### ISSUE TITLE
Expose DLP and BendersBridge

### ISSUE THREAD

**Issue by ktarplee** [StructJuMP/StructJuMP.jl#47]
I am fairly new to Julia so I am not sure what the best way is to expose these methods defined in BendersBridge.jl.   Including it (with include()) from the tests is generating redefinition warnings and of course is not easily accessible to an end user.

**Comment by joehuchette** [comment]
By expose do you mean: doing ``using StructJuMP`` makes these methods available in the namespace? Then it would be sufficient to add ``export BendersBridge, DLP`` like [this](https://github.com/StructJuMP/StructJuMP.jl/blob/616588ae3ce6b3f564fdb1ecfbff51bedae2cce4/src/StructJuMP.jl#L13-L14) (along with some documentation, preferably).

**Comment by ktarplee** [comment]
fixed in #47

**Comment by blegat** [comment]
You mean in #49 ?
