### ISSUE TITLE
Bug in PowerGrid example

### ISSUE THREAD

**Issue by frederikgeth** [StructJuMP/StructJuMP.jl#54]
in [scopf.jl](https://github.com/StructJuMP/StructJuMP.jl/blob/master/examples/PowerGrid/scopf.jl#L99) there is a curly brace `...ToLines[b]}` which should be a parenthesis.

**Comment by joehuchette** [comment]
Unable to test right now, but should be fixed by 9dda1efc5227040bed5a442a8c47e02f2616a5de. Thanks!
