### ISSUE TITLE
any better integration of PIPS?

### ISSUE THREAD

**Issue by kibaekkim** [StructJuMP/StructJuMP.jl#59]
It looks like we have to follow the comments in lines ([L1](https://github.com/StructJuMP/StructJuMP.jl/blob/master/src/StructJuMP.jl#L1), [L10](https://github.com/StructJuMP/StructJuMP.jl/blob/master/src/StructJuMP.jl#L10), and [L11](https://github.com/StructJuMP/StructJuMP.jl/blob/master/src/StructJuMP.jl#L11)) to use PIPS. Is there any better way to integrate this?

**Comment by cnpetra** [comment]
I guess so. @joehuchette, do you have any recommendation on how to do this elegantly?

**Comment by joehuchette** [comment]
We really need to extract the MPI portions of the code to a separate package (StructJuMPMPI.jl?). It shouldn't require too much new code, just some thought about how to restructure things.

I'm not exactly sure why the precompilation is causing trouble, though.

**Comment by joehuchette** [comment]
@cnpetra @kibaekkim I have created a branch here (https://github.com/StructJuMP/StructJuMP.jl/tree/no-mpi) and a separate package (https://github.com/joehuchette/StructJuMPwithMPI.jl) to try to remove StructJuMP's dependency on MPI. Take a look and see if this addresses your issues/concerns. (See https://github.com/joehuchette/StructJuMPwithMPI.jl/blob/master/README.md for usage).

**Comment by cnpetra** [comment]
works for me
