### ISSUE TITLE
StructuredConstraintRef struct seems unnecessary

### ISSUE THREAD

**Issue by jmaack24** [StructJuMP/StructJuMP.jl#71]
The JuMP.ConstraintRef struct allows takes the model type as a parameterized type provided it is a subtype of JuMP.AbstractModel.  Since this is true of StructuredModel, it seems unnecessary to create a StructJuMP specialized version of this struct.

More importantly, because there is no abstract super type for JuMP.ConstraintRef, StructJuMP's usage of its own specialized constraint reference struct means that code cannot easily work with a JuMP.Model or a StructJuMP.StructuredModel easily.

**Comment by blegat** [comment]
That makes sense, it can be replaced by `ConstraintRef{StructuredModel, Int, <:AbstractShape}`.
