### ISSUE TITLE
MethodError: no method matching _init_NLP(::StructuredModel)

### ISSUE THREAD

**Issue by cheesecakeball** [StructJuMP/StructJuMP.jl#76]
I was trying to run the example in README.md. Following error pop up:

`MethodError: no method matching _init_NLP(::StructuredModel)
Closest candidates are:
  _init_NLP(!Matched::Model) at ./.julia/packages/JuMP/MsUSY/src/nlp.jl:155`

I am new to Julia and JuMP. The version of JuMP is v0.20.1. Can someone help me with this? Thanks!

**Comment by blegat** [comment]
StructJuMP master does not support nlp yet

**Comment by cheesecakeball** [comment]
That worked! Thanks for the quick response!
